name:                gap-parser
version:             0.1.0.0
github:              "kaashif/gap-parser"
license:             GPL3
author:              "Kaashif Hymabaccus"
maintainer:          "kaashif@kaashif.co.uk"
copyright:           "2020 Kaashif Hymabaccus"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/kaashif/gap-parser>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

tests:
  gap-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gap-parser
